
# Get All Authors
GET http://localhost:4000/api/authors
Accept: application/json
User-Agent: Rest Client

###

# Get Author By Id
GET http://localhost:4000/api/authors/vivek-dutta-mishra
Accept: application/json

